/******************************************************************************
 *
 * Module: ULTRASONIC
 *
 * File Name: ultrasonic.h
 *
 * Description: Header file for the AVR ULTRASONIC driver
 *
 * Author: Kareem Ahmed Thabet
 *
 *******************************************************************************/

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

/*******************************************************************************
 *                         Includes                                            *
 *******************************************************************************/
#include"std_types.h"
#include"gpio.h"

/*******************************************************************************
 *                        Definitions                                          *
 *******************************************************************************/
#define TRIGGER_PORT_ID PORTB_ID
#define TRIGGER_PIN_ID PIN5_ID

/*******************************************************************************
 *                        Functions Prototypes                                 *
 *******************************************************************************/
/*
 * Description:
 * Initialize the ICU driver as required.
 * Setup the ICU call back function.
 * Setup the direction for the trigger pin as output pin through the GPIO driver
 */
void ULTRASONIC_init(void);

/*
 * Description: Send the Trigger pulse to the ultrasonic
 */
void ULTRASONIC_Trigger(void);

/*
 * Description
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 */
uint16 ULTRASONIC_readDistance(void);

/*
 * Description:
 * This is the call back function called by the ICU driver.
 *  This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void ULTRASONIC_edgeProcessing(void);

#endif /* ULTRASONIC_H_ */
